version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    IMAGE_REPO_NAME: static-app
    IMAGE_TAG: latest

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -o kubectl https://amazon-eks.s3.us-east-1.amazonaws.com/latest/2023-11-14/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/

  pre_build:
    commands:
      - echo Logging in to ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 955030484275.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t static-app .
      - docker tag static-app:latest 955030484275.dkr.ecr.us-east-1.amazonaws.com/static-app:latest
  post_build:
    commands:
      - echo Pushing to ECR...
      - docker push 955030484275.dkr.ecr.us-east-1.amazonaws.com/static-app:latest

      - echo Deploying to EKS...
      - aws eks update-kubeconfig --region us-east-1 --name test-cluster
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml